// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC38o24m5EnIff02PXFViwD351yzkM59hE',
    appId: '1:430854546205:web:83e7ded830ac673a2277f4',
    messagingSenderId: '430854546205',
    projectId: 'coview-c26d3',
    authDomain: 'coview-c26d3.firebaseapp.com',
    storageBucket: 'coview-c26d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMFzj7CQESbyw29A6viI0Y-ch0WVEosUU',
    appId: '1:430854546205:android:a1722ed50766f5ad2277f4',
    messagingSenderId: '430854546205',
    projectId: 'coview-c26d3',
    storageBucket: 'coview-c26d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnoc9C7SU8S4MFIngCAZmAXNkLcUpne8o',
    appId: '1:430854546205:ios:0678cce0867bcd552277f4',
    messagingSenderId: '430854546205',
    projectId: 'coview-c26d3',
    storageBucket: 'coview-c26d3.firebasestorage.app',
    iosBundleId: 'com.coview.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnoc9C7SU8S4MFIngCAZmAXNkLcUpne8o',
    appId: '1:430854546205:ios:256e1bcea2ec967c2277f4',
    messagingSenderId: '430854546205',
    projectId: 'coview-c26d3',
    storageBucket: 'coview-c26d3.firebasestorage.app',
    iosBundleId: 'com.example.coview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC38o24m5EnIff02PXFViwD351yzkM59hE',
    appId: '1:430854546205:web:d572b732cbfd4da82277f4',
    messagingSenderId: '430854546205',
    projectId: 'coview-c26d3',
    authDomain: 'coview-c26d3.firebaseapp.com',
    storageBucket: 'coview-c26d3.firebasestorage.app',
  );
}
